include: package:flutter_lints/flutter.yaml

linter:
  rules:
    matching_super_parameters: true
    prefer_single_quotes: true
    require_trailing_commas: true
    use_colored_box: true
    use_decorated_box: true
    use_super_parameters: true
